version: '3'

services:
  mysql:
    container_name: meu-vinil-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'vinil_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - app-db:/var/lib/mysql
    network_mode: host
volumes:
  app-db: